# NOTE: Replace "your-namespace" with your actual namespace!

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ezbackup-automation
  namespace: your-namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ezbackup-automation
  namespace: your-namespace
subjects:
- kind: ServiceAccount
  name: ezbackup-automation
  namespace: your-namespace
roleRef:
  # As created in install/001-cluster-role.yaml
  kind: ClusterRole
  name: ezbackup-scaler-role
  apiGroup: rbac.authorization.k8s.io